-- =============================================================================
-- Solution: OpenRTB Analyst Agent
-- Industry: Advertising & MarTech
-- Database: SF_SOLUTIONS
-- Schemas:  OPENRTB_ANALYTICS
-- =============================================================================
-- Programmatic advertising analytics with Cortex Agent.
-- Demonstrates: Dynamic Tables, Semantic Views, Snowflake CoWork Agent.
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Shared infrastructure (idempotent)
CREATE DATABASE IF NOT EXISTS SF_SOLUTIONS;
CREATE WAREHOUSE IF NOT EXISTS SF_SOLUTIONS_WH
WITH WAREHOUSE_SIZE = 'LARGE'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

USE DATABASE SF_SOLUTIONS;
USE WAREHOUSE SF_SOLUTIONS_WH;

-- Schema creation
CREATE SCHEMA IF NOT EXISTS OPENRTB_ANALYTICS;
USE SCHEMA SF_SOLUTIONS.OPENRTB_ANALYTICS;

-- =============================================================================
-- Base Tables: Raw pre-aggregated hourly bid and auction data
-- =============================================================================

CREATE OR REPLACE TABLE OPENRTB_BIDS (
__TIME TIMESTAMP_NTZ NOT NULL,
ADOMAIN VARCHAR,
ADVERTISER_NAME VARCHAR,
CAMPAIGN_NAME VARCHAR,
APP_OR_SITE VARCHAR,
APP_SITE_DOMAIN VARCHAR,
APP_SITE_NAME VARCHAR,
PUB_NAME VARCHAR,
DEVICE_TYPE VARCHAR,
DEVICE_OS VARCHAR,
DEVICE_REGION VARCHAR,
PLATFORM_BROWSER VARCHAR,
AUCTION_TYPE VARCHAR,
BID_FLOOR_BUCKET VARCHAR,
PLACEMENT_TYPE VARCHAR,
CREATIVE_TYPE VARCHAR,
BID_CNT NUMBER DEFAULT 0,
IMP_CNT NUMBER DEFAULT 0,
CLICK_REG_CNT NUMBER DEFAULT 0,
MEDIA_SPEND_USD FLOAT DEFAULT 0,
BID_PRICE_USD FLOAT DEFAULT 0,
BID_FLOOR FLOAT DEFAULT 0,
HAS_BID_FLOOR_CNT NUMBER DEFAULT 0,
VIDEO_START_CNT NUMBER DEFAULT 0,
VIDEO_COMPLETE_CNT NUMBER DEFAULT 0,
SSP_EXCHANGE VARCHAR,
SUPPLY_PATH_TYPE VARCHAR,
INTERMEDIARY_COUNT NUMBER DEFAULT 1,
SUPPLY_COST_PCT FLOAT DEFAULT 0,
CLEARING_PRICE_USD FLOAT DEFAULT 0,
BOT_SCORE FLOAT,
SUSPICIOUS_FLAG NUMBER DEFAULT 0,
DATACENTER_FLAG NUMBER DEFAULT 0,
VIEWABLE_IMP_CNT NUMBER DEFAULT 0,
VIEWABILITY_RATE FLOAT DEFAULT 0
);

CREATE OR REPLACE TABLE OPENRTB_AUCTIONS (
__TIME TIMESTAMP_NTZ NOT NULL,
APP_SITE_NAME VARCHAR,
APP_SITE_DOMAIN VARCHAR,
PUB_NAME VARCHAR,
APP_SITE_CAT VARCHAR,
AD_SIZE VARCHAR,
DEVICE_REGION VARCHAR,
DEVICE_OS VARCHAR,
DEVICE_TYPE VARCHAR,
PLATFORM_BROWSER VARCHAR,
BID_FLOOR_BUCKET VARCHAR,
PLACEMENT_TYPE VARCHAR,
AUCTION_TYPE VARCHAR,
APP_OR_SITE VARCHAR,
AD_POSITION VARCHAR,
BID_REQUEST_CNT NUMBER DEFAULT 0,
BID_FLOOR FLOAT DEFAULT 0,
HAS_BID_FLOOR_CNT NUMBER DEFAULT 0
);

-- =============================================================================
-- Dynamic Tables: Hourly aggregation for dashboard and agent queries
-- =============================================================================

CREATE OR REPLACE DYNAMIC TABLE OPENRTB_BIDS_HOURLY
TARGET_LAG = '1 day'
WAREHOUSE = SF_SOLUTIONS_WH
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
AS
SELECT
DATE_TRUNC('hour', __TIME) AS HOUR_TS,
ADOMAIN,
ADVERTISER_NAME,
CAMPAIGN_NAME,
APP_OR_SITE,
APP_SITE_DOMAIN,
APP_SITE_NAME,
PUB_NAME,
DEVICE_TYPE,
DEVICE_OS,
DEVICE_REGION,
PLATFORM_BROWSER,
AUCTION_TYPE,
BID_FLOOR_BUCKET,
PLACEMENT_TYPE,
CREATIVE_TYPE,
SUM(BID_CNT) AS TOTAL_BIDS,
SUM(IMP_CNT) AS TOTAL_IMPRESSIONS,
SUM(CLICK_REG_CNT) AS TOTAL_CLICKS,
SUM(MEDIA_SPEND_USD) AS TOTAL_SPEND_USD,
SUM(BID_PRICE_USD) AS TOTAL_BID_PRICE_USD,
SUM(BID_FLOOR) AS TOTAL_BID_FLOOR,
SUM(HAS_BID_FLOOR_CNT) AS TOTAL_HAS_FLOOR,
SUM(VIDEO_START_CNT) AS TOTAL_VIDEO_STARTS,
SUM(VIDEO_COMPLETE_CNT) AS TOTAL_VIDEO_COMPLETES,
CASE WHEN SUM(BID_CNT) > 0
THEN SUM(IMP_CNT)::FLOAT / SUM(BID_CNT)
ELSE 0 END AS WIN_RATE,
CASE WHEN SUM(IMP_CNT) > 0
THEN SUM(CLICK_REG_CNT)::FLOAT / SUM(IMP_CNT)
ELSE 0 END AS CTR,
CASE WHEN SUM(IMP_CNT) > 0
THEN SUM(MEDIA_SPEND_USD) / 1000.0 / SUM(IMP_CNT)
ELSE 0 END AS ECPM,
CASE WHEN SUM(BID_CNT) > 0
THEN SUM(BID_PRICE_USD) / 1000.0 / SUM(BID_CNT)
ELSE 0 END AS AVG_BID_PRICE,
CASE WHEN SUM(HAS_BID_FLOOR_CNT) > 0
THEN SUM(BID_FLOOR) / SUM(HAS_BID_FLOOR_CNT)
ELSE 0 END AS AVG_BID_FLOOR,
CASE WHEN SUM(VIDEO_START_CNT) > 0
THEN SUM(VIDEO_COMPLETE_CNT)::FLOAT / SUM(VIDEO_START_CNT)
ELSE 0 END AS VIDEO_COMPLETION_RATE,
SUM(CLEARING_PRICE_USD) AS TOTAL_CLEARING_PRICE_USD,
AVG(SUPPLY_COST_PCT) AS AVG_SUPPLY_COST,
SUM(SUSPICIOUS_FLAG) AS SUSPICIOUS_COUNT,
AVG(BOT_SCORE) AS AVG_BOT_SCORE,
SUM(VIEWABLE_IMP_CNT) AS TOTAL_VIEWABLE_IMPRESSIONS,
AVG(VIEWABILITY_RATE) AS AVG_VIEWABILITY,
COUNT(*) AS ROW_COUNT
FROM SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_BIDS
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16;

CREATE OR REPLACE DYNAMIC TABLE OPENRTB_AUCTIONS_HOURLY
TARGET_LAG = '1 day'
WAREHOUSE = SF_SOLUTIONS_WH
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
AS
SELECT
DATE_TRUNC('hour', __TIME) AS HOUR_TS,
APP_SITE_NAME,
APP_SITE_DOMAIN,
PUB_NAME,
APP_SITE_CAT,
AD_SIZE,
CASE WHEN DEVICE_REGION ILIKE '%/%'
THEN SPLIT_PART(DEVICE_REGION, '/', 2)
ELSE 'Unknown' END AS DEVICE_STATE,
CASE WHEN DEVICE_REGION ILIKE '%/%'
THEN SPLIT_PART(DEVICE_REGION, '/', 1)
ELSE 'Unknown' END AS DEVICE_COUNTRY,
DEVICE_OS,
DEVICE_TYPE,
PLATFORM_BROWSER,
BID_FLOOR_BUCKET,
PLACEMENT_TYPE,
AUCTION_TYPE,
APP_OR_SITE,
AD_POSITION,
SUM(BID_REQUEST_CNT) AS TOTAL_REQUESTS,
SUM(BID_FLOOR) AS TOTAL_BID_FLOOR,
SUM(HAS_BID_FLOOR_CNT) AS TOTAL_HAS_FLOOR,
CASE WHEN SUM(HAS_BID_FLOOR_CNT) > 0
THEN SUM(BID_FLOOR) / SUM(HAS_BID_FLOOR_CNT)
ELSE 0 END AS AVG_BID_FLOOR,
SUM(BID_REQUEST_CNT) / 86400.0 AS QPS_1D,
COUNT(*) AS ROW_COUNT
FROM SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_AUCTIONS
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16;

CREATE OR REPLACE DYNAMIC TABLE OPENRTB_EXECUTIVE_DAILY
TARGET_LAG = '1 day'
WAREHOUSE = SF_SOLUTIONS_WH
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
AS
SELECT
DATE_TRUNC('day', __TIME) AS DAY_TS,
SUM(BID_CNT) AS TOTAL_BIDS,
SUM(IMP_CNT) AS TOTAL_IMPRESSIONS,
SUM(CLICK_REG_CNT) AS TOTAL_CLICKS,
SUM(MEDIA_SPEND_USD) / 1000.0 AS TOTAL_SPEND,
SUM(VIDEO_START_CNT) AS TOTAL_VIDEO_STARTS,
SUM(VIDEO_COMPLETE_CNT) AS TOTAL_VIDEO_COMPLETES,
CASE WHEN SUM(BID_CNT) > 0
THEN SUM(IMP_CNT)::FLOAT / SUM(BID_CNT) ELSE 0 END AS WIN_RATE,
CASE WHEN SUM(IMP_CNT) > 0
THEN SUM(CLICK_REG_CNT)::FLOAT / SUM(IMP_CNT) ELSE 0 END AS CTR,
CASE WHEN SUM(IMP_CNT) > 0
THEN SUM(MEDIA_SPEND_USD) / 1000.0 / SUM(IMP_CNT) ELSE 0 END AS ECPM,
CASE WHEN SUM(BID_CNT) > 0
THEN SUM(BID_PRICE_USD) / 1000.0 / SUM(BID_CNT) ELSE 0 END AS AVG_BID_PRICE,
CASE WHEN SUM(HAS_BID_FLOOR_CNT) > 0
THEN SUM(BID_FLOOR) / SUM(HAS_BID_FLOOR_CNT) ELSE 0 END AS AVG_BID_FLOOR
FROM SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_BIDS
GROUP BY 1;

CREATE OR REPLACE DYNAMIC TABLE OPENRTB_ADVERTISER_PERFORMANCE
TARGET_LAG = '1 day'
WAREHOUSE = SF_SOLUTIONS_WH
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
AS
SELECT
DATE_TRUNC('day', __TIME) AS DAY_TS,
ADVERTISER_NAME,
ADOMAIN,
SUM(MEDIA_SPEND_USD) / 1000.0 AS TOTAL_SPEND,
SUM(BID_CNT) AS TOTAL_BIDS,
SUM(IMP_CNT) AS TOTAL_IMPRESSIONS,
SUM(CLICK_REG_CNT) AS TOTAL_CLICKS,
CASE WHEN SUM(IMP_CNT) > 0
THEN SUM(CLICK_REG_CNT)::FLOAT / SUM(IMP_CNT) ELSE 0 END AS CTR,
CASE WHEN SUM(IMP_CNT) > 0
THEN SUM(MEDIA_SPEND_USD) / 1000.0 / SUM(IMP_CNT) ELSE 0 END AS ECPM,
SUM(VIDEO_START_CNT) AS TOTAL_VIDEO_STARTS,
SUM(VIDEO_COMPLETE_CNT) AS TOTAL_VIDEO_COMPLETES
FROM SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_BIDS
GROUP BY 1, 2, 3;

CREATE OR REPLACE DYNAMIC TABLE OPENRTB_SPEND_BY_DEVICE
TARGET_LAG = '1 day'
WAREHOUSE = SF_SOLUTIONS_WH
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
AS
SELECT
DATE_TRUNC('hour', __TIME) AS HOUR_TS,
DEVICE_TYPE,
SUM(MEDIA_SPEND_USD) / 1000.0 AS TOTAL_SPEND,
SUM(BID_CNT) AS TOTAL_BIDS,
SUM(IMP_CNT) AS TOTAL_IMPRESSIONS
FROM SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_BIDS
GROUP BY 1, 2;

CREATE OR REPLACE DYNAMIC TABLE OPENRTB_WINRATE_BY_FLOOR
TARGET_LAG = '1 day'
WAREHOUSE = SF_SOLUTIONS_WH
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
AS
SELECT
BID_FLOOR_BUCKET,
AUCTION_TYPE,
SUM(BID_CNT) AS TOTAL_BIDS,
SUM(IMP_CNT) AS TOTAL_IMPRESSIONS,
CASE WHEN SUM(BID_CNT) > 0
THEN SUM(IMP_CNT)::FLOAT / SUM(BID_CNT) ELSE 0 END AS WIN_RATE
FROM SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_BIDS
GROUP BY 1, 2;

CREATE OR REPLACE DYNAMIC TABLE OPENRTB_SPO_ANALYSIS
TARGET_LAG = '1 day'
WAREHOUSE = SF_SOLUTIONS_WH
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
AS
SELECT
SSP_EXCHANGE,
SUPPLY_PATH_TYPE,
PUB_NAME,
COUNT(*) AS TOTAL_ROWS,
SUM(BID_CNT) AS TOTAL_BIDS,
SUM(IMP_CNT) AS TOTAL_IMPRESSIONS,
SUM(MEDIA_SPEND_USD) AS TOTAL_SPEND_USD,
SUM(CLEARING_PRICE_USD) AS TOTAL_CLEARING_PRICE_USD,
AVG(SUPPLY_COST_PCT) AS AVG_SUPPLY_COST_PCT,
AVG(INTERMEDIARY_COUNT) AS AVG_INTERMEDIARY_COUNT,
CASE WHEN SUM(BID_CNT) > 0
THEN SUM(IMP_CNT)::FLOAT / SUM(BID_CNT) ELSE 0 END AS WIN_RATE,
CASE WHEN SUM(IMP_CNT) > 0
THEN SUM(MEDIA_SPEND_USD) / SUM(IMP_CNT) ELSE 0 END AS ECPM,
CASE WHEN SUM(MEDIA_SPEND_USD) > 0
THEN SUM(CLEARING_PRICE_USD) / SUM(MEDIA_SPEND_USD)
ELSE 0 END AS CLEARING_EFFICIENCY
FROM SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_BIDS
WHERE SSP_EXCHANGE IS NOT NULL
GROUP BY 1, 2, 3;

CREATE OR REPLACE DYNAMIC TABLE OPENRTB_FRAUD_INDICATORS
TARGET_LAG = '1 day'
WAREHOUSE = SF_SOLUTIONS_WH
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
AS
SELECT
DATE_TRUNC('day', __TIME) AS DAY_TS,
DEVICE_TYPE,
PUB_NAME,
EXTRACT(HOUR FROM __TIME) AS HOUR_OF_DAY,
COUNT(*) AS TOTAL_ROWS,
SUM(BID_CNT) AS TOTAL_BIDS,
SUM(IMP_CNT) AS TOTAL_IMPRESSIONS,
SUM(CLICK_REG_CNT) AS TOTAL_CLICKS,
SUM(SUSPICIOUS_FLAG) AS SUSPICIOUS_COUNT,
SUM(DATACENTER_FLAG) AS DATACENTER_COUNT,
AVG(BOT_SCORE) AS AVG_BOT_SCORE,
MAX(BOT_SCORE) AS MAX_BOT_SCORE,
CASE WHEN SUM(IMP_CNT) > 0
THEN SUM(CLICK_REG_CNT)::FLOAT / SUM(IMP_CNT) ELSE 0 END AS CTR,
CASE WHEN COUNT(*) > 0
THEN SUM(SUSPICIOUS_FLAG)::FLOAT / COUNT(*) ELSE 0 END AS SUSPICIOUS_RATE
FROM SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_BIDS
WHERE BOT_SCORE IS NOT NULL
GROUP BY 1, 2, 3, 4;

CREATE OR REPLACE DYNAMIC TABLE OPENRTB_BID_LANDSCAPE
TARGET_LAG = '1 day'
WAREHOUSE = SF_SOLUTIONS_WH
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
AS
SELECT
DEVICE_TYPE,
DEVICE_REGION,
PLACEMENT_TYPE,
COUNT(*) AS TOTAL_ROWS,
SUM(BID_CNT) AS TOTAL_BIDS,
SUM(IMP_CNT) AS TOTAL_IMPRESSIONS,
SUM(MEDIA_SPEND_USD) / 1000.0 AS TOTAL_SPEND,
AVG(BID_PRICE_USD / NULLIF(BID_CNT, 0)) / 1000.0 AS AVG_BID_PRICE,
AVG(CLEARING_PRICE_USD / NULLIF(IMP_CNT, 0)) / 1000.0 AS AVG_CLEARING_PRICE,
PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY
CASE WHEN IMP_CNT > 0
THEN CLEARING_PRICE_USD / IMP_CNT / 1000.0 END
) AS P25_CLEARING_PRICE,
PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY
CASE WHEN IMP_CNT > 0
THEN CLEARING_PRICE_USD / IMP_CNT / 1000.0 END
) AS MEDIAN_CLEARING_PRICE,
PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY
CASE WHEN IMP_CNT > 0
THEN CLEARING_PRICE_USD / IMP_CNT / 1000.0 END
) AS P75_CLEARING_PRICE,
CASE WHEN SUM(BID_CNT) > 0
THEN SUM(IMP_CNT)::FLOAT / SUM(BID_CNT) ELSE 0 END AS WIN_RATE,
AVG(VIEWABILITY_RATE) AS AVG_VIEWABILITY
FROM SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_BIDS
WHERE CLEARING_PRICE_USD > 0
GROUP BY 1, 2, 3;

CREATE OR REPLACE DYNAMIC TABLE OPENRTB_ADVERTISER_DAILY
TARGET_LAG = '1 day'
WAREHOUSE = SF_SOLUTIONS_WH
REFRESH_MODE = FULL
INITIALIZE = ON_CREATE
AS
SELECT
DATE_TRUNC('day', __TIME) AS DAY_TS,
ADVERTISER_NAME,
SUM(BID_CNT) AS TOTAL_BIDS,
SUM(IMP_CNT) AS TOTAL_IMPRESSIONS,
SUM(CLICK_REG_CNT) AS TOTAL_CLICKS,
SUM(MEDIA_SPEND_USD) / 1000.0 AS TOTAL_SPEND,
CASE WHEN SUM(BID_CNT) > 0
THEN SUM(IMP_CNT)::FLOAT / SUM(BID_CNT) ELSE 0 END AS WIN_RATE,
CASE WHEN SUM(IMP_CNT) > 0
THEN SUM(CLICK_REG_CNT)::FLOAT / SUM(IMP_CNT) ELSE 0 END AS CTR,
CASE WHEN SUM(IMP_CNT) > 0
THEN SUM(MEDIA_SPEND_USD) / SUM(IMP_CNT) ELSE 0 END AS ECPM,
SUM(SUSPICIOUS_FLAG) AS SUSPICIOUS_COUNT,
AVG(BOT_SCORE) AS AVG_BOT_SCORE,
SUM(VIEWABLE_IMP_CNT) AS VIEWABLE_IMPRESSIONS,
AVG(VIEWABILITY_RATE) AS AVG_VIEWABILITY
FROM SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_BIDS
GROUP BY 1, 2;

-- =============================================================================
-- Semantic View: Stage for YAML upload (PUT executed by SKILL.md installer)
-- =============================================================================

CREATE STAGE IF NOT EXISTS SEMANTIC_MODEL_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stage for Cortex Analyst semantic model YAML';

-- NOTE: The semantic_model.yaml file must be uploaded to this stage before
-- calling SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML. The SKILL.md installer
-- handles this via PUT command:
--   PUT file://semantic_model.yaml @SEMANTIC_MODEL_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE
--
-- After PUT, run:
--   CALL SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML(
--       'SF_SOLUTIONS.OPENRTB_ANALYTICS',
--       SNOWFLAKE.CORTEX.READ_FILE('@SF_SOLUTIONS.OPENRTB_ANALYTICS.SEMANTIC_MODEL_STAGE/semantic_model.yaml')
--   );
--   GRANT SELECT ON SEMANTIC VIEW SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_ANALYTICS TO ROLE PUBLIC;

-- =============================================================================
-- Cortex Agent: Snowflake CoWork
-- =============================================================================

CREATE OR REPLACE AGENT SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_ANALYST
COMMENT = 'Programmatic advertising analytics agent for OpenRTB bid and auction data'
PROFILE = '{"display_name":"OpenRTB Analyst"}'
FROM SPECIFICATION
$$
models:
  orchestration: "auto"

instructions:
  response: |
    You are an expert programmatic advertising analyst with deep knowledge of
    OpenRTB 2.6, DSP/SSP mechanics, and ad tech metrics. You help users
    understand their bid performance, auction dynamics, and campaign efficiency.

    When answering questions:
    - Always provide specific numbers and percentages
    - Compare metrics across dimensions when relevant
    - Flag anomalies or notable patterns
    - Suggest optimization actions when data reveals opportunities
    - Use industry terminology correctly (eCPM, CTR, win rate, bid floor, etc.)

tools:
  - tool_spec:
      type: "cortex_analyst_text_to_sql"
      name: "query_openrtb_data"

tool_resources:
  query_openrtb_data:
    semantic_view: "SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_ANALYTICS"
    execution_environment:
      type: "warehouse"
      warehouse: "SF_SOLUTIONS_WH"
$$;

GRANT USAGE ON AGENT SF_SOLUTIONS.OPENRTB_ANALYTICS.OPENRTB_ANALYST
    TO ROLE PUBLIC;

-- Output URLs
SELECT 'https://app.snowflake.com/' || LOWER(CURRENT_ORGANIZATION_NAME()) || '/'
    || LOWER(CURRENT_ACCOUNT_NAME())
    || '/#/agents/database/SF_SOLUTIONS/schema/OPENRTB_ANALYTICS/agent/OPENRTB_ANALYST/details'
    AS AGENT_URL;
